landuage: node_js
node_js:
  - "11"
notifications:
  email:
    recipients:
      - 519495771@qq.com
  on_success: change
  on_failure: always
cache:
  directories:
    - node_modules
before_script:
  - npm run bootstrap
script:
  - npm run build
  - npm run test
after_success:
  - npm run coveralls
git:
  depth: 5
secure: "h33Vrqxs8/w+vsQAnZUnHe9z1+UNFMpW24ajo1/JX8UT7DwQXNHSHnGnBvdsZvUyvQDF8oRceC6r7WL9QEbjiNicTyRPUDkcrx4zlYyQbdRvj3A3rjuiU86eMtf3+PcvVWnJuHZj3wt6dggNgYB4MKBwtmtDCUYpz7ln3zCe4c4fmTFxXnams1j2n8XnatcN2ZGZBv+zYkG2i9n+zPrCAYMNllOGHR1Alu8KhRowOw/qr32zzmUvLogs573fK6bR8toZnmRhLqIxLOwAw5uIRdPdACYsyIX3l6/SVySIy3EOuwuzIWcQ7ujitKsFMhXR+w99tYLRsilNVZl0MgiKEeE+v1q+uWisfwIsC78nEZta3JGd4FaXz3CU0KIkPakbYJmi9gG///Ig+af2PQQxx1YWuZBuvBvrf2ZvXmAF+uEjou8WENCQjz/FibuFUmUELHxQ+AJbtuV/tawfBaLH+5QqXh6o2PD5cA0cZ/qb7GCio1XzPHyfl0pyyZmDqkg0DrXzfRjd3by9oXN/Onac2RmDl0QgP83TI3T03KL8gJ7ZVVqx+gcyeKqGl8Afyf5EDyGvHqWUondrQDhr0Py0fb1rcdQXxtUQJWNmFYfMUcRczrWCP6h1Hdx4GbdEgAHIpAiX7mYqQTFBeCbUkzhGyJnhpQ3VJR8f5Teju4dOmBg="
