landuage: node_js
node_js:
  - "11"
cache:
  directories:
    - node_modules
before_script:
  - npm run bootstrap
script:
  - npm run build
  - npm run test
after_success:
  - npm run coveralls
git:
  depth: 5
