landuage: node_js
node_js:
  - "11"
cache:
  directories:
    - node_modules
before_install:
  - npm install typescript && npm run lerna && lerna bootstrap
install:
  - npm install
script:
  - npm run build
